### ISSUE TITLE
大佬请教下测试网的问题

### ISSUE THREAD

**Issue by ygcool** [JFJun/helium-go#1]
1、若要创建测试网地址的话，version应该是多少？  [链接](https://github.com/JFJun/helium-go/blob/3ba12c838350e0859e706afd289e1372eff95914/keypair/keypair.go#L136)

2、如果要签名测试网交易的话，现在库是不是还没支持？

期待回复，谢谢

**Comment by JFJun** [comment]
> 1、若要创建测试网地址的话，version应该是多少？ [链接](https://github.com/JFJun/helium-go/blob/3ba12c838350e0859e706afd289e1372eff95914/keypair/keypair.go#L136)
> 
> 2、如果要签名测试网交易的话，现在库是不是还没支持？
> 
> 期待回复，谢谢

TESTNET=0x10,可以在这里查询：https://github.com/helium/helium-js/blob/a8cd4915d9ca55d19cc0294725b1485acc340bee/packages/crypto/src/NetType.ts。测试网交易我没有试过哦，你可以自己尝试一下 @ygcool

**Comment by ygcool** [comment]
谢谢，能加个联系方式吗？ 或者电报

**Comment by JFJun** [comment]
> 谢谢，能加个联系方式吗？ 或者电报

微：JFJun_12 @ygcool
